[package]
name = "advent3"
version = "0.1.0"
authors = ["arborelia <gh@arborelia.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-display = "0.6.0"